// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_weather_png);    // assets/Weather.png
LV_IMG_DECLARE(ui_img_temp_png);    // assets/temp.png
LV_IMG_DECLARE(ui_img_humi_png);    // assets/humi.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets/co2.png
LV_IMG_DECLARE(ui_img_tvoc_png);    // assets/tvoc.png
LV_IMG_DECLARE(ui_img_makerfabs_png);    // assets/makerfabs.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
